services:
  - type: web
    name: poscus-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: 8726110607:AAE0EYK8V_wr0T5fE2vHIeXTBtZXD85SNyg
      - key: ADMIN_IDS
        value: "6548871396"
      - key: RENDER_URL
        value: https://poscus-predicter.onrender.com
      - key: ADMIN_TOKEN
        value: VC5SA9AT0H2010
